task_name: 'train_dataset'
output_dir: 'model_output'
n_epochs: 2
accelerator: 'gpu'
monitor_metric: 'exact_match'

model_kwargs:
  model_name: 'distilbert-base-uncased'
  max_grad_norm: 3.0
  freeze: 80
  fmt: 'float32'

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 2e-5
  weight_decay: 1e-2

scheduler: 'torch.optim.lr_scheduler.CosineAnnealingLR'
scheduler_kwargs:
  T_max: 10
  eta_min: 1e-5

losses:
  - name: 'CrossEntropy'
    weight: 1.0
    loss_fn: 'torch.nn.CrossEntropyLoss'
    loss_kwargs: {reduction: 'mean', label_smoothing: 0.001}

data_config:
  batch_size: 128
  n_workers: 4